#!/usr/bin/env python3
"""
Generate font16x28.h — a custom 16x28 bitmap font for SSD1306 (page-oriented).

Each glyph is defined as a 16x28 ASCII-art grid (the visible area), then
padded to 16x32 with 2px top and 2px bottom padding before conversion to
SSD1306 page format: 4 pages of 16 bytes each (column-major within page,
LSB = top pixel within page).

The 2px top/bottom padding leaves room for the half-degree dot indicator
above the digits and for the square frame of the long-press overlay.

Glyphs covered: 0-9, space, dash, H, I, L, O

Glyph sources:
  - Built-in ASCII art definitions (default)
  - BDF font files (--bdf <file.bdf>): extracts needed glyphs, centers/crops
    to 16x28. Use --preview to see the result before generating.

Usage:
    python3 gen_font16x28.py > ../main/font16x28.h
    python3 gen_font16x28.py --bdf somefont.bdf > ../main/font16x28.h
    python3 gen_font16x28.py --bdf somefont.bdf --preview
"""

import sys
import argparse

W = 16
H_VISIBLE = 28  # visible glyph height
H_TOTAL = 32    # total height including padding
PAD_TOP = 2     # empty rows above glyph
PAD_BOT = 2     # empty rows below glyph

def parse_grid(art):
    """Parse a 28-line ASCII-art string into a 32x16 grid with 2px top/bottom padding.
    '#' or 'X' = pixel on, anything else = off."""
    lines = art.strip('\n').split('\n')
    assert len(lines) == H_VISIBLE, f"Expected {H_VISIBLE} lines, got {len(lines)}"
    grid = []
    # Top padding
    for _ in range(PAD_TOP):
        grid.append([0] * W)
    # Visible area
    for line in lines:
        row = []
        for i in range(W):
            ch = line[i] if i < len(line) else '.'
            row.append(1 if ch in ('#', 'X') else 0)
        grid.append(row)
    # Bottom padding
    for _ in range(PAD_BOT):
        grid.append([0] * W)
    return grid

def grid_to_pages(grid):
    """Convert 16x32 grid to 4 pages of 16 bytes each (SSD1306 format)."""
    pages = []
    for page in range(4):
        page_data = []
        for col in range(W):
            byte = 0
            for bit in range(8):
                y = page * 8 + bit
                if grid[y][col]:
                    byte |= (1 << bit)
            page_data.append(byte)
        pages.append(page_data)
    return pages

def grid_to_art(grid):
    """Convert grid back to ASCII art for comments (full 32 rows including padding)."""
    lines = []
    for y in range(H_TOTAL):
        lines.append(''.join('#' if grid[y][x] else '.' for x in range(W)))
    return lines


# ── Glyph definitions ──
# Each glyph is a 16-wide x 32-tall ASCII art block.
# '#' = pixel on, '.' = pixel off

GLYPHS = {}

GLYPHS['0'] = """
....########....
...##########...
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
...##########...
....########....
"""

GLYPHS['1'] = """
.......##.......
......###.......
.....####.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
....########....
....########....
"""

GLYPHS['2'] = """
....########....
...##########...
..##........##..
............##..
............##..
............##..
............##..
............##..
...........##...
..........##....
.........##.....
........##......
.......##.......
......##........
.....##.........
....##..........
...##...........
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..############..
..############..
"""

GLYPHS['3'] = """
....########....
...##########...
..##........##..
............##..
............##..
............##..
............##..
............##..
............##..
............##..
............##..
............##..
.....########...
.....########...
............##..
............##..
............##..
............##..
............##..
............##..
............##..
............##..
............##..
............##..
............##..
..##........##..
...##########...
....########....
"""

GLYPHS['4'] = """
..##......##....
..##......##....
..##......##....
..##......##....
..##......##....
..##......##....
..##......##....
..##......##....
..##......##....
..##......##....
..##......##....
..##......##....
..############..
..############..
..........##....
..........##....
..........##....
..........##....
..........##....
..........##....
..........##....
..........##....
..........##....
..........##....
..........##....
..........##....
..........##....
..........##....
"""

GLYPHS['5'] = """
..############..
..############..
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##########....
..###########...
............##..
............##..
............##..
............##..
............##..
............##..
............##..
............##..
............##..
............##..
............##..
..##........##..
...##########...
....########....
"""

GLYPHS['6'] = """
....########....
...##########...
..##........##..
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##########....
..###########...
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
...##########...
....########....
"""

GLYPHS['7'] = """
..############..
..############..
............##..
...........##...
...........##...
..........##....
..........##....
.........##.....
.........##.....
........##......
........##......
.......##.......
.......##.......
......##........
......##........
......##........
.....##.........
.....##.........
.....##.........
.....##.........
.....##.........
.....##.........
.....##.........
.....##.........
.....##.........
.....##.........
.....##.........
.....##.........
"""

GLYPHS['8'] = """
....########....
...##########...
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
...##########...
...##########...
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
...##########...
....########....
"""

GLYPHS['9'] = """
....########....
...##########...
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
...###########..
....##########..
............##..
............##..
............##..
............##..
............##..
............##..
............##..
............##..
............##..
............##..
............##..
..##........##..
...##########...
....########....
"""

GLYPHS[' '] = """
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""

GLYPHS['-'] = """
................
................
................
................
................
................
................
................
................
................
................
................
...##########...
...##########...
................
................
................
................
................
................
................
................
................
................
................
................
................
................
"""

GLYPHS['H'] = """
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..############..
..############..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
..##........##..
"""

GLYPHS['I'] = """
....########....
....########....
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
.......##.......
....########....
....########....
"""

GLYPHS['L'] = """
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..##............
..############..
..############..
"""

GLYPHS['O'] = GLYPHS['0']  # identical

# ── Character ordering ──
CHARS = "0123456789 -HILO"


# ── BDF font import ──

def parse_bdf(filename):
    """Parse a BDF font file, return dict of {encoding_int: (bbw, bbh, bbx, bby, [hex_rows])}."""
    glyphs = {}
    with open(filename) as f:
        lines = f.readlines()

    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if line.startswith('STARTCHAR'):
            encoding = None
            bbw = bbh = bbx = bby = 0
            bitmap_rows = []
            i += 1
            while i < len(lines) and not lines[i].strip().startswith('ENDCHAR'):
                l = lines[i].strip()
                if l.startswith('ENCODING'):
                    encoding = int(l.split()[1])
                elif l.startswith('BBX'):
                    parts = l.split()
                    bbw, bbh, bbx, bby = int(parts[1]), int(parts[2]), int(parts[3]), int(parts[4])
                elif l == 'BITMAP':
                    i += 1
                    while i < len(lines) and not lines[i].strip().startswith('ENDCHAR'):
                        bitmap_rows.append(lines[i].strip())
                        i += 1
                    continue  # don't increment i again, ENDCHAR check will handle it
                i += 1
            if encoding is not None:
                glyphs[encoding] = (bbw, bbh, bbx, bby, bitmap_rows)
        i += 1
    return glyphs


def bdf_glyph_to_grid(bdf_glyph):
    """Convert a BDF glyph to a 16x28 grid, centered horizontally, aligned to baseline.

    BDF glyphs have a bounding box (bbw x bbh) at offset (bbx, bby) relative
    to the origin. bby is typically negative for descenders.

    We place the glyph centered in 16 columns and vertically positioned so that
    the baseline sits near row 24 (leaving ~4 rows for descenders in the 28-row
    visible area).
    """
    bbw, bbh, bbx, bby, hex_rows = bdf_glyph

    # Decode hex rows into a bbw x bbh pixel grid
    raw = []
    for hexrow in hex_rows:
        val = int(hexrow, 16)
        # BDF hex is MSB-first, padded to byte boundary
        n_bits = len(hexrow) * 4
        row = []
        for bit in range(n_bits):
            row.append(1 if (val >> (n_bits - 1 - bit)) & 1 else 0)
        # Trim or pad to bbw
        row = row[:bbw] + [0] * max(0, bbw - len(row))
        raw.append(row)

    # Position in 16x28 grid
    # Baseline at row 22 (0-indexed within the 28-row visible area)
    # This leaves rows 23-27 for descenders and bottom padding
    BASELINE = 22

    # The glyph's bottom-left is at (bbx, bby) relative to origin.
    # bby > 0 means the glyph bottom is above the baseline.
    # bby < 0 means the glyph extends below the baseline (descender).
    # The glyph top is at bby + bbh - 1 above baseline origin.
    glyph_top_y = BASELINE - (bby + bbh - 1)  # row in our grid where glyph starts

    # Center horizontally
    glyph_left_x = (W - bbw) // 2 + bbx

    grid = [[0] * W for _ in range(H_VISIBLE)]
    for row_idx, row_data in enumerate(raw):
        y = glyph_top_y + row_idx
        if y < 0 or y >= H_VISIBLE:
            continue
        for col_idx, pixel in enumerate(row_data):
            x = glyph_left_x + col_idx
            if 0 <= x < W and pixel:
                grid[y][x] = 1

    return grid


def load_bdf_glyphs(bdf_file, chars):
    """Load specific characters from a BDF file, return dict of {char: 28-line art string}."""
    bdf_glyphs = parse_bdf(bdf_file)
    result = {}

    for ch in chars:
        enc = ord(ch)
        if enc not in bdf_glyphs:
            print(f"Warning: character '{ch}' (U+{enc:04X}) not found in BDF file, using blank",
                  file=sys.stderr)
            result[ch] = '\n'.join(['.' * W] * H_VISIBLE)
            continue

        grid = bdf_glyph_to_grid(bdf_glyphs[enc])
        # Convert grid to art string
        art_lines = []
        for row in grid:
            art_lines.append(''.join('#' if p else '.' for p in row))
        result[ch] = '\n'.join(art_lines)

    return result


# ── Generate C header ──
def main():
    parser = argparse.ArgumentParser(description='Generate font16x28.h for SSD1306')
    parser.add_argument('--bdf', help='Import glyphs from a BDF font file instead of built-in art')
    parser.add_argument('--preview', action='store_true',
                        help='Print ASCII art preview to stderr and exit (no C output)')
    args = parser.parse_args()

    grids = {}

    if args.bdf:
        # Load from BDF file
        bdf_arts = load_bdf_glyphs(args.bdf, CHARS)
        for ch in CHARS:
            # Override built-in glyphs with BDF versions
            GLYPHS[ch] = bdf_arts[ch]

    for ch in CHARS:
        grids[ch] = parse_grid(GLYPHS[ch])

    if args.preview:
        for ch in CHARS:
            label = ch if ch != ' ' else 'SPACE'
            print(f"── '{label}' ──", file=sys.stderr)
            art = grid_to_art(grids[ch])
            for line in art:
                print(f"  {line}", file=sys.stderr)
            print(file=sys.stderr)
        return

    print("// Auto-generated by tools/gen_font16x28.py — do not edit by hand")
    print("// Custom 16x28 font for SSD1306 (page-oriented, stored as 16x32 with 2px padding)")
    print("// Each glyph: 4 pages x 16 bytes = 64 bytes")
    print("// Page-major, column-minor within each page")
    print("// Visible area: 16x28 pixels (rows 2-29), rows 0-1 and 30-31 are padding")
    print(f"// Covers: {repr(CHARS)}")
    print(f"// {len(CHARS)} glyphs, {len(CHARS) * 64} bytes total")
    print()
    print("#pragma once")
    print("#include <stdint.h>")
    print()
    print(f"#define FONT16X28_GLYPH_COUNT {len(CHARS)}")
    print()
    print("// Map ASCII char to glyph index")
    print("static inline int font16x28_index(char c) {")
    print("    switch(c) {")
    for i, ch in enumerate(CHARS):
        if ch == ' ':
            print(f"        case ' ': return {i};")
        elif ch == "'":
            print(f"        case '\\'': return {i};")
        else:
            print(f"        case '{ch}': return {i};")
    print(f"        default: return {CHARS.index(' ')};  // space")
    print("    }")
    print("}")
    print()
    print(f"static const uint8_t font16x28[{len(CHARS)}][4][16] = {{")
    for i, ch in enumerate(CHARS):
        grid = grids[ch]
        pages = grid_to_pages(grid)
        art = grid_to_art(grid)
        label = ch if ch != ' ' else 'SPACE'
        print(f"    // [{i}] '{label}'")
        # Print ASCII art as comments
        for line in art:
            print(f"    // {line}")
        print(f"    {{")
        for p in range(4):
            vals = ", ".join(f"0x{b:02X}" for b in pages[p])
            print(f"        {{{vals}}},")
        print(f"    }},")
    print("};")

if __name__ == "__main__":
    main()
